apiVersion: v1
kind: Pod
metadata:
  name: app1-pod
  labels:
    app: app1
spec:
  containers:
  - name: app1-container
    image: zagirox/app1:v1
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
    ports:
    - containerPort: 3000
    command: ["node", "node-app1.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
