apiVersion: v1
kind: Pod
metadata:
  name: app2-pod
  labels:
    app: app2
spec:
  containers:
  - name: app2-container
    image: zagirox/app2:v1
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
    ports:
    - containerPort: 3000
    command: ["node", "node-app2.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer